version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/src/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - minio
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/homework_db
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
      MINIO_HOST: minio:9000
    restart: always
    networks:
      - backend-network


  postgres:
    image: postgres
    ports:
      - "5440:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: homework_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 15
    restart: always
    networks:
      - backend-network


  minio:
    image: bitnami/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    volumes:
      - minio_data:/data
    restart: always
    networks:
      - backend-network


volumes:
  minio_data:
    driver: local
  pgdata:
    driver: local

networks:
  backend-network:
    driver: bridge